config/routes.rb
Rails.application.routes.draw do
  root 'profile#home'
  
  # resources :boards
  post 'cards/newcard', to: 'cards#create'

  resources :lists, only: [:create, :update]
  resources :cards, only: [:create, :update]
  resources :collaborations, only: [:create, :update]
  
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  post '/boards/create', to: 'boards#create'
  get '/boards/index', to: 'boards#index'
  resources :users do
    resources :boards
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list, optional: true
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user
  has_many :feeds
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_card, only: [:update, :destroy]


  def create
    @card = Card.new(card_params)
    if @card.save
      Feed.create(board_id: @card.list.board.id, card_id: @card.id, user_id: current_user.id, list_id: @card.list_id, action: " created card #{@card.content} in #{@card.list.title}")
      render json: @card
    end
  end

  def update
    if params[:update_type] == "toggle_check"
      @card.update(checked: !@card.checked)
      Feed.create(board_id: @card.list.board.id, card_id: @card.id, user_id: current_user.id, list_id: @card.list_id, action: " marked card #{@card.content} in #{@card.list.title} #{'un' if !@card.checked}completed.")
    else
      @card.update(card_params)
      Feed.create(board_id: @card.list.board.id, card_id: @card.id, user_id: current_user.id, list_id: @card.list_id, action: " updated card in #{@card.list.title}")
    end
    redirect_to user_board_path(current_user, @board)
  end

  def destroy
    @card.destroy
    redirect_to user_board_path(current_user, @board)
  end

  private

  def set_card
    @card = Card.find_by(id: params[:id])
    @board = @card.list.board
  end

  def card_params
    params.require(:card).permit(:content, :list_id)
  end
end

app/views/cards/_form.html.erb
<%= form_for @new_card do |f| %>

  <% if @new_card.errors.any? %>
      <h2><%= pluralize(@new_card.errors.count, "error") %> prohibited this card from being saved:</h2>

    <ul>
      <% @new_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.hidden_field :list_id, value: list.id %>

  <%= f.text_field :content, placeholder: 'Add a card...', required: 'required', class: 'transparent-input card input', autocomplete: "off" %>

<% end %>

app/views/cards/_users.html.erb
<%= form_for User.new, :url => collaborations_path do |f| %>
  <%= f.hidden_field :card_id, value:card.id %>
  <%= f.hidden_field :board_id, value:card.list.board.id %>
  <%= f.text_field :email, list: "names", placeholder: 'search users',required: 'required',autofocus: 'autofocus' %>
  <datalist id="names">
    <% User.all.each do |user| %>
      <option value="<%=user.email%>" id="<%=user.id%>">
    <% end %>
  </datalist>
  <%= f.submit 'add', class: 'ui mini button' %>
<% end %>